; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	F:\Buckland_SourceCode\VS8 projects\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
